name: CI

on:
  push:

jobs:
  generate:
    name: Generate project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: accelerator-ci
      - name: Checkout CLI
        uses: actions/checkout@v3
        with:
          repository: pivotal/acc-engine
          ssh-key: ${{ secrets.ACC_SSH }}
          path: acc-engine
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install YTT
        run: |
          wget -O- https://carvel.dev/install.sh > install.sh
          sudo bash install.sh
          ytt version
      - name: Build CLI
        run: |
          cd acc-engine/cli
          ./build.sh
      - name: Register Accelerator
        run: |
          cd acc-engine/cli
          java -jar target/cli-1.3.0-SNAPSHOT-exec.jar register hello-spring --from-location file://$GITHUB_WORKSPACE
      - name: Generate
        run: |
          cd acc-engine/cli
          java -jar target/cli-1.3.0-SNAPSHOT-exec.jar run --values ../../accelerator-ci/accelerator-test/values.json --output generated-project hello-spring
      - name: Upload Generated Project
        uses: actions/upload-artifact@v3
        with:
          name: generated-project
          path: acc-engine/cli/generated-project
  test-compile:
    name: Test Compile
    needs: [generate]
    runs-on: ubuntu-latest
    steps:
      - name: Download generated project
        uses: actions/download-artifact@v3
        with:
          name: generated-project
      - name: Compile
        run: |
          ./gradlew compileJava
  run-tests:
    name: Run Tests
    needs: [ generate ]
    runs-on: ubuntu-latest
    steps:
      - name: Download generated project
        uses: actions/download-artifact@v3
        with:
          name: generated-project
      - name: Compile
        run: |
          ./gradlew test